repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: file-contents-sorter
        args: [--unique]
        files: '\.gitignore'
      - id: requirements-txt-fixer
        args: [requirements-dev.txt]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cabal-fmt
        name: "format cabal with cabal-fmt"
        entry: cabal-fmt
        language: system
        types: [file, text]
        files: ^.*\.cabal$
        args: [--check, --inplace]
      - id: stylish-haskell
        name: "format haskell with stylish-haskell"
        entry: stylish-haskell
        language: system
        types: [haskell]
        args: [--inplace]

# Do not run local hooks on pre-commit CI:
ci:
  skip: [cabal-fmt, stylish-haskell]
